### PR TITLE
Make it compile typescript code

### PR DESCRIPTION
**Pull request by tlbdk**

### CODE REVIEW

**Review by mex — APPROVED** [review]

**Review by mex — APPROVED** [review]

**Comment by ofweb** [comment]
The type files and the js files end up in two different places. The js files are in `build/dist/src`, but the type files are in `build/dist`. So TS cannot find the types.

**Comment by mex** [comment]
That could be fixed by moving either the src files or the types in the prepack step after having run the compilation.

**Comment by ofweb** [comment]
> That could be fixed by moving either the src files or the types in the prepack step after having run the compilation.

I can't see that being done node-backend Is it because of the build script is different? `"build": "build src",` vs eg 
`"build:js": "babel src --out-dir ./build/dist/ --extensions '.ts' --source-maps  --ignore '**/*.d.ts'",`
`"build:types": "tsc --emitDeclarationOnly",`

**Comment by mex** [comment]
Yeah, object validator uses the build script from `node-test`.

I'm not sure whether it's better to move the src files or the types. Probably easier to move the src files one level up.

**Comment by tlbdk** [comment]
Typescript behaves different if there are only files in src/ then it will not create sub folders in the out folder, if there are files outside it will create the src folder. so I just added a dummy file in bin to fix this.

**Comment by tlbdk** [comment]
We are missing rootDir: '.' in tsconfig.json, if it's missing tsc will try to get what's it should be. Also it has nothing to do with rootDirs options:

https://github.com/microsoft/TypeScript/issues/8245

**Pull request merged**
